### ISSUE TITLE
SSL error when I'm not using SSL

### ISSUE THREAD

**Issue by andrewgdotcom** [sirensolutions/chembl#2]
I tried to run the importer as described in the README, but it throws an SSL error. This is interesting, as neither the ES nor the API connections are SSL...

```
andrewg@chembl:~/chembl$ python import.py -es http://localhost:$ES_PORT -api http://api.chemicalfingerprint.siren.io
no chembl database available
Traceback (most recent call last):
  File "import.py", line 317, in <module>
    print('deleting', index_name, es.indices.delete(index=index_name, ignore=404, timeout='300s'))
  File "/home/andrewg/.local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/andrewg/.local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 201, in delete
    params=params)
  File "/home/andrewg/.local/lib/python2.7/site-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/andrewg/.local/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 73, in perform_request
    raise SSLError('N/A', str(e), e)
elasticsearch.exceptions.SSLError: ConnectionError(("bad handshake: Error([('SSL routines', 'SSL23_GET_SERVER_HELLO', 'unknown protocol')],)",)) caused by: SSLError(("bad handshake: Error([('SSL routines', 'SSL23_GET_SERVER_HELLO', 'unknown protocol')],)",))
```

**Comment by emepyc** [comment]
The script assumes SSL connection to ES: https://github.com/sirensolutions/chembl/blob/mp/import.py#L279

btw, please run your own fingerprint api (spinning up a docker container as explained in the README). The reasons for this: 1) it is going to be much faster to load the data and 2) there are a few fingerprints that fail (I still have to figure out why) which results in different responses for a local API vs the one hosted in gce

**Comment by andrewgdotcom** [comment]
That makes no sense. The protocol is supplied as part of the URL, so why does ssl need to be set in the code also?

**Comment by apierleoni** [comment]
because the script is setup to run with a self signed ssl, so it is specifying the use_ssl flag and the verify false. 
If you want it to work with both an HTTPS and HTTP endpoint both the api and the import script needs to be modified accordingly. The API runs in HTTPS, because kibi does that, otherwise it is not callable from a browser without a proxy. the import script is just adapting  to the same api, without overcomplicating things

**Comment by andrewgdotcom** [comment]
`The API runs in HTTPS, because kibi does that`

Only if you have searchguard installed. The demo docker images have by default, but the standalone packages do not.

**Comment by jccq** [comment]
I believe searchguard will be needed as we'll make this a public deployment

**Comment by andrewgdotcom** [comment]
@jccq that's a side issue. The issue at hand here is that I pass an http: url to the script and it silently upgrades it to https:

**Comment by colmose** [comment]
Pass a `--ssl=false` flag to the .py script and default to `true`?

**Comment by apierleoni** [comment]
this was built to work with safeguard on in the container or the demo site. 
If you want to make it more refined, you'll need to make ssl conditional in both the loading script and the API.

**Comment by apierleoni** [comment]
@colmose 
there are 3 cases:
- HTTP
- HTTPS with valid certs
- HTTPS with self signed certs

**Comment by andrewgdotcom** [comment]
Self-signed certs can be handled with a flag, that's not an issue. But what I don't understand is that the URL `https://site:port/whatever` is being passed to the function call:

```
es = Elasticsearch(ES_URL,
                   use_ssl=True,
                   verify_certs=False,
                   http_auth=ES_AUTH,
connection_class=RequestsHttpConnection)
```

And yet we have `use_ssl` passed also, which seems to be redundant.

The documentation here (https://elasticsearch-py.readthedocs.io/en/master/) implies that 'use_ssl' is only required when passing the connection info as separate `host`, `port` etc., not when passing a URL. So we should just get rid of it.

**Comment by andrewgdotcom** [comment]
And BTW, by default the fingerprint API is running in plaintext:

```
andrewg@chembl:~/chembl$ curl http://localhost:8009
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
andrewg@chembl:~/chembl$ 
```
